#*********************************************************************
# Copyright (c) Intel Corporation 2021
# SPDX-License-Identifier: Apache-2.0
#*********************************************************************/

name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build -f "Dockerfile" --tag vprodemo.azurecr.io/rpc-go:${{ github.sha }} --tag vprodemo.azurecr.io/rpc-go:latest .
      - name: Docker Login
        if: ${{ github.ref == 'refs/heads/main' }}      
        uses: docker/login-action@v1.6.0
        with:
          registry: vprodemo.azurecr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: true
      - name: Push the Docker image to the registry
        if: ${{ github.ref == 'refs/heads/main' }}      
        run: docker push vprodemo.azurecr.io/rpc-go:${{ github.sha }}
      - name: Push the Docker image to the registry
        if: ${{ github.ref == 'refs/heads/main' }}      
        run: docker push vprodemo.azurecr.io/rpc-go:latest