name: .NET

on:
  push:
    branches: [main, release, 2.x.x]
  pull_request:
    branches: [main, release, 2.x.x]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
      with:
        egress-policy: audit

    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Setup .NET
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
      with:
        dotnet-version: 6.0.x
    - name: Build rpc as library
      run: go build -buildmode=c-shared -o rpc.so ./cmd/rpc   
    - name: Restore dependencies
      run: cd samples/dotnet && dotnet restore
    - name: Build
      run: cd samples/dotnet && dotnet build --no-restore

