#*********************************************************************
# Copyright (c) Intel Corporation 2021
# SPDX-License-Identifier: Apache-2.0
#*********************************************************************/

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
permissions:
  contents: read

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, windows-2022, ubuntu-22.04, ubuntu-20.04]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Format
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi        
      - name: Run go vet
        run: go vet ./...
      - name: Install Test Converter and run tests
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        run: |
          export GOPATH="$HOME/go/"
          export PATH=$PATH:$GOPATH/bin
          go install github.com/jstemmer/go-junit-report/v2@latest
          go test -v 2>&1 ./... | go-junit-report -set-exit-code > rpc-go-unit.xml

      - name: run the tests with coverage
        run: go test ./... -coverprofile=coverage.out -covermode=atomic
      
      - uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        name: Upload Coverage Results
        
      # Runs a single command using the runners shell
      - name: build go
        if: ${{ matrix.os == 'windows-2019' }}
        run: go build -o rpc.exe ./cmd
      
      # Runs a single command using the runners shell
      - name: build go
        if: ${{ matrix.os != 'windows-2019' }}
        run: go build -o rpc ./cmd

      - name: GitHub Upload Release Artifacts
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        with:
          name: rpc-go-unit
          path: rpc-go-unit.xml
