#*********************************************************************
# Copyright (c) Intel Corporation 2021
# SPDX-License-Identifier: Apache-2.0
#*********************************************************************/

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
permissions:
  contents: read

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, windows-2022, ubuntu-22.04, ubuntu-20.04]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Format
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi        
      - name: Run go vet
        run: go vet ./...
      - name: Install Test Converter and run tests
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        run: |
          export GOPATH="$HOME/go/"
          export PATH=$PATH:$GOPATH/bin
          go install github.com/jstemmer/go-junit-report/v2@latest
          go test -v 2>&1 ./... | go-junit-report -set-exit-code > rpc-go-unit.xml

      - name: run the tests with coverage
        run: go test ./... -coverprofile=coverage.out -covermode=atomic
      
      - uses: codecov/codecov-action@84508663e988701840491b86de86b666e8a86bed # v4.3.0
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        name: Upload Coverage Results
        
      # Runs a single command using the runners shell
      - name: build go
        if: ${{ matrix.os == 'windows-2019' }}
        run: go build -ldflags "-w -s" -o rpc.exe ./cmd
      
      # Runs a single command using the runners shell
      - name: build go
        if: ${{ matrix.os != 'windows-2019' }}
        run: go build -ldflags "-w -s" -o rpc ./cmd

      - name: GitHub Upload Release Artifacts
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        with:
          name: rpc-go-unit
          path: rpc-go-unit.xml
      
