#*********************************************************************
# Copyright (c) Intel Corporation 2021
# SPDX-License-Identifier: Apache-2.0
#*********************************************************************/

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, ubuntu-18.04, ubuntu-20.04]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: run the tests
        run: go test ./... -coverprofile=coverage.out -covermode=atomic
      
      - uses: codecov/codecov-action@v1.0.14
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        name: Upload Coverage Results
        
      # Runs a single command using the runners shell
      - name: build go
        if: ${{ matrix.os == 'windows-2019' }}
        run: go build -o rpc.exe ./cmd
      
      # Runs a single command using the runners shell
      - name: build go
        if: ${{ matrix.os != 'windows-2019' }}
        run: go build -o rpc ./cmd

        

      # Runs a set of commands using the runners shell
      # - name: GitHub Upload Release Artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: RPC_${{ matrix.os }}
      #     path: |
      #         rpc
      #         rpc.exe
